openapi: 3.0.1
info:
  title: VerifyName API
  version: 1.0.0
paths:
  /v2/vasps:
    get:
      operationId: VerifyNameListVASP
      summary: List VASP API
      description: >
        This API provides a list of VASPs registered with VerifyVASP.

        The list is used during the withdrawal process to select the Beneficiary
        VASP. After retrieving the VASP list through this API, the vaspId field
        of the selected VASP can be used when initiating a verification request.


        ### VASP Eligibility Criteria
          The list includes your VASP and other VASPs that meet the following criteria:
          - The VASP is a member of VerifyVASP or another Travel Rule vendor.
          - The VASP is capable of handling asset transfers.
      tags:
        - VN Enclave API
      parameters:
        - name: protocol
          in: query
          schema:
            type: string
            enum:
              - TRAVEL-RULE
              - VERIFY-NAME
            description: |
              Unique identifier of request verification.  
              Must be a UUID format.
            example: VERIFY-NAME
      responses:
        '200':
          description: 200 Response
          content:
            application/json:
              schema:
                type: object
                required:
                  - verificationResult
                properties:
                  verificationResult:
                    type: object
                    description: >
                      The values of the **verification_result** has to be one of
                      the following values.

                      - **MATCHED**: The value of request from beneficiary VASP
                      is matched with the information from originating VASP. 

                      - **MISMATCHED**: The value of request from beneficiary
                      VASP is mismatched with the information from originating
                      VASP.

                      - **SKIPPED**: The beneficiary VASP does not provide the
                      value of request or The originating VASP does not provide
                      the value of request.
                    required:
                      - ticker
                      - network
                      - address
                      - tag
                      - dti
                      - tx_hash
                    properties:
                      ticker:
                        type: string
                        description: |
                          The symbol of the virtual asset to be transferred.
                        example: ETH
                      network:
                        type: string
                        description: >
                          The network of the virtual asset to be transferred.
                          The network field can be implemented conditionally.
                          Valid values for this field can be found [here]().
                        example: ETHEREUM
                      address:
                        type: string
                        description: |
                          The address of the wallet storing the virtual asset.
                        example: '0xBb3fd383d1C5540E52EF0A7bcb9433375793aEAF'
                      tag:
                        type: string
                        nullable: true
                        description: >
                          The wallet address tag(secondary address such as XRP,
                          XLM, EOS, etc...), regardless VerifyOriginator or
                          VerifyBeneficiary.
                        example: '3256697931'
                      dti:
                        type: string
                        description: >
                          Digital Token Identifier (DTI) based on the ISO 24165
                          standard.
                        example: 4H95J0R2X
                      tx_hash:
                        type: string
                        description: >
                          Unique identifier of the transaction. If the value of
                          **VerifyOriginator** is **type**, this field must be
                          required.
                        example: >-
                          8a54d58ca4100112a5430818776d74898f2232770bae03046862575cb851a042
                      debtor:
                        type: object
                        properties:
                          name:
                            type: string
                            example: JHON DOE
                          supplementary_data:
                            type: object
                        example:
                          name: JHON DOE
                          supplementary_data:
                            envelope:
                              name:
                                first_name: JHON
                                last_name: DOE
                          identification:
                            private_identification:
                              date_and_place_of_birth:
                                date_of_birth: '1990-01-01'
              examples:
                successExample:
                  value:
                    verification_results:
                      ticker: MATCHED
                      network: MISMATCHED
                      address: SKIPPED
                      tag: SKIPPED
                      tx_hash: SKIPPED
                      dti: SKIPPED
                    debtor:
                      name: HONG KIL DONG
                      supplementary_data:
                        envelope:
                          name:
                            first_name: GIL DONG
                            last_name: HONG
                          identification:
                            private_identification:
                              date_and_place_of_birth:
                                birth_date: '2025-01-01'
        '400':
          description: 400 Bad Request Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: |
                      Error message.  

                      It could be returned in the following cases.  
                        1. Invalid input parameters.  
                        2. Missing Required Parameters.
                    example: MISSING-VERIFICATION-UUID
                  message:
                    type: string
                    description: |
                      Explanation about the error that is returned in **code**.
                    example: verificationUuid` is required.
              examples:
                401ErrorExample:
                  value:
                    code: INVALID-ENCLAVE-MODE
                    message: >-
                      mode is invalid value. The allowed modes [TR, VN1_CALL,
                      VN1_RESPONSE, VN2]
        '408':
          description: 408 Request Timeout Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: >
                      Error message.  


                      It could be returned in the following cases.   When a
                      timeout occurs during the processing of a request.
                    example: REQUEST-TIMEOUT
                  message:
                    type: string
                    description: |
                      Explanation about the error that is returned in **code**.
                    example: timeout of 5000ms exceeded
              examples:
                408ErrorExample:
                  value:
                    code: REQUEST-TIMEOUT
                    message: timeout of 5000ms exceeded
  /v1/vasps/self:
    get:
      summary: Get VASP ID API
      description: |
        This API returns your VASP's VASP ID.
      operationId: getVaspId
      tags:
        - VN Enclave API
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  vaspId:
                    type: string
                    description: |
                      Unique identifier of VASP.
                    example: '15952089931162060684'
              examples:
                successfulExample:
                  value:
                    vaspId: '15952089931162058999'
        '400':
          description: 400 Bad Request Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: >
                      Error message.   - Invalid input parameters - Missing
                      Required Parameters - Inactive VASP
                    example: MISSING-VERIFICATION-UUID
                  message:
                    type: string
                    description: |
                      Explanation about the error that is returned in code
                    example: verificationUuid is required.
              examples:
                400Errorexample:
                  value:
                    code: MISSING-REQUIRED-BENEFICIARY-INFO
                    message: '`requiredBeneficiaryInfo` is required.'
        '404':
          description: 404 Resource Not Found Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: >
                      Error message.   It could be returned in the following
                      cases:   - When request with a non-existent resources is
                      provided.
                    example: VERIFICATION-NOT-FOUND
                  message:
                    type: string
                    description: |
                      Explanation about the error that is returned in CODE.
                    example: >-
                      Verification(9faab87c-54a6-4145-baa9-7a3a42d7410c) is not
                      found
              examples:
                404Errorexample:
                  value:
                    code: VERIFICATION-NOT-FOUND
                    message: >-
                      Verification(9faab87c-54a6-4145-baa9-7a3a42d7410c) is not
                      found
        '408':
          description: 408 Request Timeout Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: >
                      Error message.   It could be returned in the following
                      cases:   When a timeout occurs during the processing of a
                      request.
                    example: REQUEST-TIMEOUT
                  message:
                    type: string
                    description: |
                      Explanation about the error that is returned in code.
                    example: timeout of 5000ms exceeded
              examples:
                408Errorexample:
                  value:
                    code: REQUEST-TIMEOUT
                    message: timeout of 5000ms exceeded
  /v2/owner-verifications:
    post:
      operationId: VNrequestOwnerVerification
      tags:
        - VN Enclave API
      summary: Request Owner Verification API
      description: >
        - VASP can use this API to verify the Beneficiary address or TxHash of
        Originator.

        - Your VASP can verify details using optional fields such as network,
        tag, dti etc.

        - Your VASP can call this API to verify the originator when your VASP
        detect the deposit of virtual assets or verify the beneficiary before
        executing the virtual asset transfer transaction. 


        ### Owner Verification Result

        - The result of the verification is returned in the response body of the
        API.

        - The verification results for the following items — ticker, network,
        address, tx_hash, dti, name, birth_date, date_of_incorporation, and
        organisation_identification — can be returned as one of the following
        values: 
          - MATCHED
          - MISMATCHED
          - SKIPPED
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - supplementary_data
              properties:
                supplementary_data:
                  type: object
                  required:
                    - envelope
                  properties:
                    envelope:
                      type: object
                      required:
                        - vasp_id
                        - type
                        - ticker
                        - address
                      properties:
                        vasp_id:
                          type: string
                          description: >
                            Unique identifier of Originator or Beneficiary
                            VASP..
                          example: '15952089931162060684'
                        type:
                          type: string
                          enum:
                            - VerifyOriginator
                            - VerifyBeneficiary
                          description: "Indication of verification type. Acceptable type values are one of\_**VerifyOriginator**,\_**VerifyBeneficiary**.\n"
                          example: VerifyOriginator
                        ticker:
                          type: string
                          description: |
                            The symbol of the virtual asset to be transferred.
                          example: ETH
                        network:
                          type: string
                          description: >
                            The network of the virtual asset to be transferred.
                            The network field can be implemented conditionally.
                            Valid values for this field can be found [here]().
                          example: ETHEREUM
                        address:
                          type: string
                          description: |
                            The address of the wallet storing the virtual asset.
                          example: '0xBb3fd383d1C5540E52EF0A7bcb9433375793aEAF'
                        tag:
                          type: string
                          nullable: true
                          description: >
                            The wallet address tag(secondary address such as
                            XRP, XLM, EOS, etc...), regardless VerifyOriginator
                            or VerifyBeneficiary.
                          example: '3256697931'
                        dti:
                          type: string
                          description: >
                            Digital Token Identifier (DTI) based on the ISO
                            24165 standard.
                          example: 4H95J0R2X
                        tx_hash:
                          type: string
                          description: >
                            Unique identifier of the transaction. If the value
                            of **VerifyOriginator** is **type**, this field must
                            be required.
                          example: >-
                            8a54d58ca4100112a5430818776d74898f2232770bae03046862575cb851a042
                        creditor:
                          type: object
                          description: >
                            An object containing information about the Owner's
                            information when the type is **VerifyBeneficiary**.
                          properties:
                            name:
                              type: string
                              description: |
                                The name of the Owner.
                              example: JHON DOE
                            supplementary_data:
                              type: object
                              properties:
                                name:
                                  type: object
                                  properties:
                                    first_name:
                                      type: string
                                      description: |
                                        The first name of the Owner.
                                      example: JHON
                                    last_name:
                                      type: string
                                      description: |
                                        The last name of the Owner.
                                      example: DOE
                            identification:
                              type: object
                              description: >
                                An object containing information about the
                                Owner's identification.
                              properties:
                                private_identification:
                                  type: object
                                  properties:
                                    date_and_place_of_birth:
                                      type: object
                                      properties:
                                        birth_date:
                                          type: string
                                          description: >
                                            Date of birth.  

                                            The format of this field must follow
                                            "YYYY-MM-DD"
                                          example: '1985-03-14'
                                organisation_identification:
                                  type: object
                                  description: >
                                    An object containing information about the
                                    legal organisation identification.
                                  required:
                                    - supplementary_data
                                  properties:
                                    supplementary_data:
                                      type: object
                                      required:
                                        - envelope
                                      properties:
                                        envelope:
                                          type: object
                                          required:
                                            - date_of_incorporation
                                          properties:
                                            date_of_incorporation:
                                              type: string
                                              description: |
                                                Date of incorporation.
                                              example: '2025-01-01'
                                    lei:
                                      type: string
                                      description: |
                                        Legal Entity Identifier (LEI).
                                      example: 506700GE1G29325QX363
                                    bic:
                                      type: string
                                      description: >
                                        Business Identifier Code (BIC). A code
                                        defined in accordance with the ISO 9362
                                        standard for identifying financial and
                                        non-financial institutions.

                                        - also known as a SWIFT code, is an 8-11
                                        character code used to identify banks
                                        and their branches globally.
                                      example: HBUKGB4B
                                    other:
                                      type: object
                                      description: >
                                        MATCHED is returned only if both the
                                        provided identification and issuer
                                        exactly match the values stored in the
                                        Enclave server.
                                      required:
                                        - identification
                                        - issuer
                                      properties:
                                        identification:
                                          type: string
                                          description: |
                                            Business Registration Number.
                                          example: 5493001KJTIIGC8Y1R12
                                        issuer:
                                          type: string
                                          description: >
                                            Issuing Authority for the Business
                                            Registration Number
                                          example: ISO17442
                        debtor:
                          type: object
                          description: >
                            An object containing information about the Owner's
                            information when the type is **VerifyBeneficiary**.
                          properties:
                            name:
                              type: string
                              description: |
                                The name of the Owner.
                              example: JHON DOE
                            supplementary_data:
                              type: object
                              properties:
                                name:
                                  type: object
                                  properties:
                                    first_name:
                                      type: string
                                      description: |
                                        The first name of the Owner.
                                      example: JHON
                                    last_name:
                                      type: string
                                      description: |
                                        The last name of the Owner.
                                      example: DOE
                            identification:
                              type: object
                              description: >
                                An object containing information about the
                                Owner's identification.
                              properties:
                                private_identification:
                                  type: object
                                  properties:
                                    date_and_place_of_birth:
                                      type: object
                                      properties:
                                        birth_date:
                                          type: string
                                          description: >
                                            Date of birth.  

                                            The format of this field must follow
                                            "YYYY-MM-DD"
                                          example: '1985-03-14'
                                organisation_identification:
                                  type: object
                                  description: >
                                    An object containing information about the
                                    legal organisation identification.
                                  required:
                                    - supplementary_data
                                  properties:
                                    supplementary_data:
                                      type: object
                                      required:
                                        - envelope
                                      properties:
                                        envelope:
                                          type: object
                                          required:
                                            - date_of_incorporation
                                          properties:
                                            date_of_incorporation:
                                              type: string
                                              description: |
                                                Date of incorporation.
                                              example: '2025-01-01'
                                    lei:
                                      type: string
                                      description: |
                                        Legal Entity Identifier (LEI).
                                      example: 506700GE1G29325QX363
                                    bic:
                                      type: string
                                      description: >
                                        Business Identifier Code (BIC). A code
                                        defined in accordance with the ISO 9362
                                        standard for identifying financial and
                                        non-financial institutions.

                                        - also known as a SWIFT code, is an 8-11
                                        character code used to identify banks
                                        and their branches globally.
                                      example: HBUKGB4B
                                    other:
                                      type: object
                                      description: >
                                        MATCHED is returned only if both the
                                        provided identification and issuer
                                        exactly match the values stored in the
                                        Enclave server.
                                      required:
                                        - identification
                                        - issuer
                                      properties:
                                        identification:
                                          type: string
                                          description: |
                                            Business Registration Number.
                                          example: 5493001KJTIIGC8Y1R12
                                        issuer:
                                          type: string
                                          description: >
                                            Issuing Authority for the Business
                                            Registration Number
                                          example: ISO17442
            examples:
              requestExamples:
                value:
                  supplementarty_data:
                    envelope:
                      vasp_id: '15952089931162060684'
                      type: VerifyBeneficiary
                      ticker: ETH
                      network: ETH
                      address: '0x5811001506550d8356a215be229c15b6ef371a9b'
                  creditor:
                    name: HONG KIL DONG
                    supplementary_data:
                      envelope:
                        name:
                          first_name: GIL DONG
                          last_name: HONG
                        identification:
                          private_identification:
                            date_and_place_of_birth:
                              birth_date: '2025-01-01'
      responses:
        '200':
          description: 200 Response
          content:
            application/json:
              schema:
                type: object
                required:
                  - request_id
                  - verification_results
                  - verified_at
                properties:
                  request_id:
                    type: string
                    description: >
                      A unique identifier for the Owner Verification request.

                      The format of `request_id` must follow the UUID v4
                      standard.
                    example: 4615aa9d-ac64-4997-a9e6-0e772c57c7ef
                  verificateion_results:
                    type: object
                    description: >
                      The values of the **verification_result** has to be one of
                      the following values.

                      - **MATCHED**: The value of request from beneficiary VASP
                      is matched with the information from originating VASP. 

                      - **MISMATCHED**: The value of request from beneficiary
                      VASP is mismatched with the information from originating
                      VASP.

                      - **SKIPPED**: The beneficiary VASP does not provide the
                      value of request or The originating VASP does not provide
                      the value of request.
                    required:
                      - ticker
                      - network
                      - address
                      - tag
                      - dti
                      - tx_hash
                    properties:
                      ticker:
                        type: string
                        description: |
                          The symbol of the virtual asset to be transferred.
                        example: ETH
                      network:
                        type: string
                        description: >
                          The network of the virtual asset to be transferred.
                          The network field can be implemented conditionally.
                          Valid values for this field can be found [here]().
                        example: ETHEREUM
                      address:
                        type: string
                        description: |
                          The address of the wallet storing the virtual asset.
                        example: '0xBb3fd383d1C5540E52EF0A7bcb9433375793aEAF'
                      tag:
                        type: string
                        nullable: true
                        description: >
                          The wallet address tag(secondary address such as XRP,
                          XLM, EOS, etc...), regardless VerifyOriginator or
                          VerifyBeneficiary.
                        example: '3256697931'
                      dti:
                        type: string
                        description: >
                          Digital Token Identifier (DTI) based on the ISO 24165
                          standard.
                        example: 4H95J0R2X
                      tx_hash:
                        type: string
                        description: >
                          Unique identifier of the transaction. If the value of
                          **VerifyOriginator** is **type**, this field must be
                          required.
                        example: >-
                          8a54d58ca4100112a5430818776d74898f2232770bae03046862575cb851a042
                      debtor:
                        type: object
                        properties:
                          name:
                            type: string
                            example: JHON DOE
                          supplementary_data:
                            type: object
                        example:
                          name: JHON DOE
                          supplementary_data:
                            envelope:
                              name:
                                first_name: JHON
                                last_name: DOE
                          identification:
                            private_identification:
                              date_and_place_of_birth:
                                date_of_birth: '1990-01-01'
                  verified_at:
                    type: string
                    description: |
                      The timestamp when the verification was verified.
                    example: >-
                      2021-09-27T01:48:40.326Z || 2021-09-27T01:48:40.326+00:00
                      || 20210927T014840.326Z
              examples:
                successExample1:
                  value:
                    mode: SYNC
                    verificationResult: VERIFIED
        '400':
          description: 400 Bad Request Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: |
                      Error message.  

                      It could be returned in the following cases.  
                        1. Invalid input parameters.  
                        2. Missing Required Parameters.
                    example: MISSING-VERIFICATION-UUID
                  message:
                    type: string
                    description: |
                      Explanation about the error that is returned in **code**.
                    example: verificationUuid` is required.
              examples:
                401ErrorExample:
                  value:
                    code: MISSING-REQUIRED-BENEFICIARY-INFO
                    message: '`requiredBeneficiaryInfo` is required.'
components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
  parameters:
    Authorization:
      name: Authorization
      in: header
      required: true
      description: |
        Bearer token for authorization.
      schema:
        type: string
        description: Bearer token for authorization.
        example: Bearer <VEGA_VERIFICATION_AUTHORIZATION_TOKEN>
